# -*- coding: utf-8 -*-
"""Last_Parkinson_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-Ot5VgasAorV4SqrLsS7_ULpJ5hQKwc
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
debasisdotcom_parkinson_disease_detection_path = kagglehub.dataset_download('debasisdotcom/parkinson-disease-detection')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

import seaborn as sns
import matplotlib.pyplot as plt

"""## Data Info"""

import os
df=pd.read_csv(os.path.join(debasisdotcom_parkinson_disease_detection_path, 'Parkinsson disease.csv'))
df.head()

import pandas as pd
import os

# Use the correct path from the kagglehub download
file_path = os.path.join(debasisdotcom_parkinson_disease_detection_path, 'Parkinsson disease.csv')
df_test = pd.read_csv(file_path)

# Preprocess the sample (remove name and status)
# Note: This requires the 'pipeline' variable from the training section to be defined
try:
    X_sample = df_test.drop(columns=['name', 'status'])
    sample = X_sample.iloc[0:1]

    # Make prediction using the trained pipeline
    prediction = pipeline.predict(sample)[0]
    prob = pipeline.predict_proba(sample)[0][1]

    print("Auto Test Prediction:", "Parkinson Detected" if prediction == 1 else "Healthy")
    print(f"Confidence: {prob:.4f}")
except NameError:
    print("Error: 'pipeline' is not defined. Please run the cell that defines and fits the pipeline first (e.g., cell E1l8tn7aEuh9).")

print(df.shape)
print(df.info())

df.isnull().sum()

df['status'] == 0

# To test in the notebook, we use standard python instead of streamlit (st)
try:
    # Use the first row of X as sample data
    sample_data = X.iloc[0:1]

    # Use the trained pipeline to predict
    prediction = pipeline.predict(sample_data)[0]
    prob = pipeline.predict_proba(sample_data)[0][1]

    print(f"Test Sample Prediction: {'Parkinson Detected' if prediction == 1 else 'Healthy'}")
    print(f"Confidence: {prob:.4f}")
except NameError:
    print("Error: 'X' or 'pipeline' is not defined. Please run the data processing and model training cells first.")

# Drop non-feature columns
# errors='ignore' prevents crashing if the columns were already dropped
X = df.drop(columns=['name', 'status'], errors='ignore')

# Take one row
sample = X.iloc[5]
",".join(map(str, sample.values))

parkinson_indices = df[df['status'] == 1].index
print(parkinson_indices)

healthy_indices = df[df['status'] == 0].index
print(healthy_indices)

print("Parkinson range:", parkinson_indices.min(), "to", parkinson_indices.max())
print("Healthy range:", healthy_indices.min(), "to", healthy_indices.max())

df['status'].value_counts(normalize=True)

"""1 --> positive parkinson

0 --> Healthy
"""

sns.countplot(x='status', data=df)
plt.title("Target Distribution")
plt.show()

plt.figure(figsize=(12,8))
sns.heatmap(df.drop('name', axis=1).corr(), cmap='coolwarm')
plt.title("Feature Correlation")
plt.show()

"""## Preproccesing"""

df = df.drop(columns=['name'], errors='ignore')

#split fet & Trg
X = df.drop(columns=['status'])
y = df['status']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', SVC(probability=True))
])

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

models = {
    "SVM": SVC(probability=True),
    "RandomForest": RandomForestClassifier(),
    "LogisticRegression": LogisticRegression(max_iter=1000)
}

"""Multiple Model_selection"""

#cross validation
from sklearn.model_selection import cross_val_score

for name, model in models.items():
    pipe = Pipeline([
        ('scaler', StandardScaler()),
        ('model', model)
    ])

    scores = cross_val_score(pipe, X, y, cv=5, scoring='f1')
    print(f"{name}: {scores.mean():.4f}")

#evaluation
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

#hyper tunning
from sklearn.model_selection import GridSearchCV

param_grid = {
    'model__C': [0.1, 1, 10],
    'model__kernel': ['linear', 'rbf']
}

grid = GridSearchCV(pipeline, param_grid, cv=5, scoring='f1')
grid.fit(X_train, y_train)

print(grid.best_params_)

import shap
import numpy as np

# Wrap prediction function
predict_fn = lambda x: pipeline.predict_proba(x)

# Summarize background for speed
background = shap.kmeans(X_train, 5)
explainer = shap.KernelExplainer(predict_fn, background)

# Calculate SHAP values
shap_values = explainer.shap_values(X_test)

# Handle different possible return formats from KernelExplainer
if isinstance(shap_values, list):
    # If list, take class 1
    shap_val_array = np.array(shap_values[1])
elif len(shap_values.shape) == 3:
    # If 3D array (samples, features, classes), take class 1
    shap_val_array = shap_values[:, :, 1]
else:
    shap_val_array = np.array(shap_values)

features_array = X_test.values

# Final check to ensure alignment
if shap_val_array.shape == features_array.shape:
    shap.summary_plot(shap_val_array, features_array, feature_names=X_test.columns)
else:
    print(f"Shape mismatch: SHAP {shap_val_array.shape} vs Features {features_array.shape}")

!pip install streamlit pyngrok

import joblib
import os

# Create the models directory if it doesn't exist
os.makedirs("models", exist_ok=True)

# Based on your previous cells, the model is stored in 'pipeline'
joblib.dump(pipeline, "models/parkinson_model.pkl")
print("Model saved successfully in 'models/parkinson_model.pkl'")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# import joblib
# 
# # Load model (make sure you saved it before)
# model = joblib.load("models/parkinson_model.pkl")
# 
# st.title("Parkinson Detection AI")
# 
# st.write("Enter patient features below:")
# 
# # Example input (simplified for now)
# input_data = st.text_area("Input Features (comma separated)")
# 
# if st.button("Predict"):
#     try:
#         data = np.array([float(i) for i in input_data.split(",")]).reshape(1, -1)
# 
#         prediction = model.predict(data)[0]
#         prob = model.predict_proba(data)[0][1]
# 
#         if prediction == 1:
#             st.error(f"⚠️ Parkinson Detected (Confidence: {prob:.2f})")
#         else:
#             st.success(f"✅ Healthy (Confidence: {1 - prob:.2f})")
# 
#     except:
#         st.warning("❗ Please enter valid numeric values")

from pyngrok import ngrok

# Replace 'YOUR_AUTHTOKEN_HERE' with the token from https://dashboard.ngrok.com/get-started/your-authtoken
ngrok.set_auth_token("39m0BpLcYn3xhAA07UnHwICK4Jt_5sh59kjp91bM1ej4erbZr")

try:
    public_url = ngrok.connect(8501)
    print(f"Public URL: {public_url}")
except Exception as e:
    print(f"Error: {e}\n\nNote: You must set your ngrok authtoken above to fix this.")

!streamlit run app.py &>/content/logs.txt &

